/** All audience-facing text (except chat messages, which live in src/data/demo.ts). */
export const content = {
  conceptLabel: 'Concept demo • Sample data',

  problem: {
    headline: 'Great products. Too many messages.',
  },
  inbox: {
    headline: 'Every conversation. One workspace.',
    listTitle: 'Inbox',
    openSuffix: 'open',
    customerPanelTitle: 'Customer',
    lastActiveLabel: 'Last active',
    channelLabel: 'Channel',
    handlingLabel: 'Handling',
    interestLabel: 'Interested in',
  },
  chat: {
    typingLabel: 'Assistant is typing',
    assistantName: 'Store assistant',
    aiTag: 'AI',
    inputPlaceholder: 'Message…',
    inStockLabel: 'In stock',
    inventoryCheckTitle: 'Inventory check',
    inventorySource: 'From merchant product info',
    deliveryReceivedTitle: 'Delivery details received',
    deliveryReceivedFields: ['Name', 'Address', 'Phone'],
    deliveryReceivedHint: 'Preparing your order for approval',
    orderDraftTitle: 'Order draft started',
    orderDraftHint: 'Collecting delivery details',
  },
  order: {
    headline: 'From conversation to order.',
    subtext: 'You approve before it moves forward.',
    title: 'Order',
    sectionTitle: 'Orders',
    customerLabel: 'Customer',
    itemLabel: 'Item',
    deliveryLabel: 'Delivery',
    totalLabel: 'Total',
    sizeLabel: 'Size',
    quantityLabel: 'Quantity',
    approveButton: 'Approve order',
    approvedButton: 'Order approved',
    statusPending: 'Pending approval',
    statusApproved: 'Approved',
  },
  takeover: {
    headline: 'Automation, with you in control.',
    attention: 'Needs your attention',
    attentionHint: 'Policy exception request',
    takeOverButton: 'Take over',
    aiHandling: 'AI handling',
    humanHandling: 'Human handling',
    aiPreparing: 'AI is preparing a reply',
    pausedTitle: 'Automated replies paused',
    pausedHint: 'You are now replying personally.',
    composerPlaceholder: 'Write a reply…',
    autoReplyLabel: 'Auto-replies',
    autoReplyOn: 'On',
    autoReplyPaused: 'Paused',
  },
  overview: {
    headline: 'A clear view of every conversation.',
    openConversations: 'Open conversations',
    aiHandling: 'AI handling',
    humanHandling: 'Human handling',
    ordersApproved: 'Orders approved',
    byChannel: 'Conversations by channel',
    dashboardTitle: 'Overview',
  },
  closing: {
    headline: 'More time for your business.',
    subtext: 'AI-assisted conversations. Human-controlled orders.',
    footer: 'Product concept • Prototype demonstration',
  },
};
